
encryption_key: someRandomBINARYKEY
mailer:
  server: xxx
  username: xxx
  password: sxxx

vat: false
require_state_in_address: true

# tax_per_state_id is a field for tax being applied at the state level or country wide level in "TaxRate model"
tax_per_state_id: true

uses_resque_for_background_emails: false


# Set this up with your Google Analytics Code for Devopment
google:
  analytics_code: false

paypal:
  ip: 192.168.0.1
  login: xxx
  password: xxx
  signature: xxx
