
encryption_key: someRandomBINARYKEY
mailer:
  server: mail.example.com
  username: someLOGIN
  password: s0meth1ngs3cr3t

vat: false
require_state_in_address: true

# tax_per_state_id is a field for tax being applied at the state level or country wide level in "TaxRate model"
tax_per_state_id: true

uses_resque_for_background_emails: false


# Set this up with your Google Analytics Code for Devopment
google:
  analytics_code: false
